default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: api-appointment_dev

test:
  <<: *default
  database: api-appointment_test

production:
  <<: *default
  database: api-appointment
